apiVersion: 1

datasources:
  - name: PV-PostgreSQL
    uid: pv-postgres
    type: postgres
    url: pv-db:5432
    user: pv
    secureJsonData:
      password: pv
    jsonData:
      database: pv
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: true
    editable: true
