apiVersion: 1

datasources:
  - name: PV-PostgreSQL
    uid: pv-postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: pv-db:5432
    user: pv
    secureJsonData:
      password: pv
    jsonData:
      database: pv
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
