apiVersion: 1

datasources:
  - name: Demand-PostgreSQL
    uid: demand-postgres
    type: grafana-postgresql-datasource
    access: proxy
    url: demand-db:5432
    user: demand
    secureJsonData:
      password: demand
    jsonData:
      database: demand
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
