apiVersion: 1

datasources:
  - name: PV-SQLite
    uid: pv-sqlite
    type: frser-sqlite-datasource
    access: proxy
    jsonData:
      path: /var/lib/grafana/data/pv.db
    isDefault: true
    editable: true
