apiVersion: 1

datasources:
  - name: PV-PostgreSQL
    uid: pv-postgres
    type: postgres
    url: pv-db:5432
    database: pv_data
    user: pv_admin
    secureJsonData:
      password: pv_secure_2024
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
    isDefault: true
    editable: true
